### PR TITLE
Migrate to Toptal

### PR DESCRIPTION
**Pull request by mingthegit**
This PR migrates gitignore.io service to Toptal with rebranding.

https://gitignore.io will be 301-redirected to https://www.toptal.com/developers/gitignore

### CODE REVIEW

**Comment by joeblau** [comment]
This looks amazing!

**Comment by mingthegit** [comment]
> This looks amazing!

**Comment by HanKruiger** [comment]
Not sure if this is the right place for this question, but what's the story here? Did Toptal acquire `gitignore.io`? How will this affect the future of the service?

**Comment by achwedyk** [comment]
@HanKruiger thank you for asking.
Yes, Toptal has acquired gitignore.io some time ago. We were working on migrating it to our infrastructure. We've updated the branding, did multiple UI and UX improvements, removed the ads, updated the documentation and refreshed the list of `.gitignore` templates.
We've released that to production on Tuesday, June 2nd.
Now, this great open-source project got corporate backing, we still plan to support it.
Please file any issues. PRs are very welcome.

**Comment by HanKruiger** [comment]
Sounds good! Thanks for clearing that up. 🙂 Congrats on the acquisition! 🎉

**Comment by afucher** [comment]
Why move the url to toptal?

**Comment by lpalgarvio** [comment]
It is is fine to be patron to the project and have the company showcased in the projects page and github.
However I dont really like that the URL changed. It hurts the project's promotion.
A much much longer URL brings no advantage vs a short URL. This is a no-brainer.

Also you mention no adds, but what is that scrolling on the footer of the website?
Please explain. @achwedyk

Also the claim that the project is receiving much support doesn't seem to be accurate.
Looking at git logs, it seems it was more active during the days of @joeblau back in 2019 and 2018.
What happened to him? Is this connected to the acquisition and change of URL?

As a contributor in the past, and seeing a project 8 years old going this direction, makes me upset.
I will ask that you change this path, and put the company serving the project, and not the other way around.

Thank you

**Comment by lpalgarvio** [comment]
image

**Comment by lpalgarvio** [comment]
image

**Pull request merged**
