### PR TITLE
Create th.json

### PR DESCRIPTION
**Pull request by DekThaiInChina**
_**Thai language for gitignore.io for Thai people**_

### CODE REVIEW

**Comment by HeyXiaoLong** [comment]
**Finally, Thai language is available.**

**Review by HeyXiaoLong — CHANGES_REQUESTED** [review]
**Finally, Thai language is available.**

**Review by MaNeeTranslator — CHANGES_REQUESTED** [review]
It's a good start. For Thai people with language support

**Review by MaNeeTranslator — APPROVED** [review]
It's a good start. For Thai people with language support

**Review by HeyXiaoLong — APPROVED** [review]
Finally, Thai language is available.

**Review by MaNeeTranslator — APPROVED** [review]
It's a good start. For Thai people with language support

**Comment by DekThaiInChina** [comment]
request a new pull

**Pull request closed without merging**
